/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.xavier.csci;

public class App {
    public String getGreeting() {

        return "Hello world.";
    }
    public String getGreeting2() {

        return "Hello universe.";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());
        System.out.println(new App().getGreeting2());
    }
}
